name: Build slideio windows and macos python packages

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, windows-2019]
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Display Python version
      run: python --version

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Add slideio conan remote
      run: conan remote add slideio ${{ secrets.CONAN_REMOTE }}
      
    - name: Login to slideio conan remote
      run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r slideio ${{ secrets.CONAN_USER }}

    - name: Conan remote
      run: conan remote list

    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: chekout conan recipes
      run: git clone 'https://gitlab.com/bioslide/conan-recipes.git' conan-recipes

    - name: install python distributions
      working-directory: ./conan-recipes
      run: python deploy-python-dists.py

    - name: Install conan dependencies
      run: python install.py -a conan
      
    - name: build python packages
      working-directory: ./src/py-bind
      run: python build_slideio_dists.py "${{ github.workspace }}/conan-recipes/py.txt"

    - name: Archive python packagess
      uses: actions/upload-artifact@v2
      with:
        name: python-dist
        path: |
          ./src/py-bind/dist